export const ENV = {
  NUMERO_CELULAR: process.env.NEXT_PUBLIC_NUMERO_CELULAR,
  CORREO_ATENCION: process.env.NEXT_PUBLIC_CORREO_ATENCION,
  CORREO_MESA_PARTES: process.env.NEXT_PUBLIC_CORREO_MESA_PARTES,
};